### ISSUE TITLE
Not working ....?

### ISSUE THREAD

**Issue by murpholinox** [charliebury/eTrack#26]
[murphy@eva03 test]$ python /home/murphy/Bins/RIDL/runRIDL.py -i inputFile.txt -pco
Traceback (most recent call last):
  File "/home/murphy/Bins/RIDL/runRIDL.py", line 3, in <module>
    from checkDependencies import checkDependencies
ImportError: No module named checkDependencies
[murphy@eva03 test]$ ls GH7-data/
GH7-10.mtz            GH7-1.mtz  GH7-5.mtz  GH7-9.mtz
GH7-11.mtz            GH7-2.mtz  GH7-6.mtz
GH7-1-fromRefmac.mtz  GH7-3.mtz  GH7-7.mtz
GH7-1-fromRefmac.pdb  GH7-4.mtz  GH7-8.mtz
[murphy@eva03 test]$ cat inputFile.txt 
dir ./RIDL-testrun1/

INITIALDATASET
name1 GH7-1
mtz1 ./GH7-data/GH7-1.mtz
mtzlabels1 F_FROMDIALS1
pdb1 ./GH7-data/GH7-1-fromRefmac.pdb
RfreeFlag1 FreeR_flag
dose1 1.11

LATERDATASET
name2 GH7-2, GH7-3
mtz2 ./GH7-data/GH7-2.mtz, ./GH7-data/GH7-3.mtz
mtzlabels2 F_FROMDIALS2, F_FROMDIALS3
dose2 3.27, 5.43

PHASEDATASET
name3 GH7-1
mtz3 ./GH7-data/GH7-1-fromRefmac.mtz
phaseLabel PHIC
FcalcLabel FC

**Comment by charliebury** [comment]
This appears to be an issue with relative versus absolute paths. I have added a new commit (https://github.com/GarmanGroup/RIDL/commit/33f9652a7da289e7e29a10b35fc97a96fc62a64b) such that:
`python path/to/loc/runRIDL.py --dependencies`

should now run to completion

**Comment by charliebury** [comment]
I have added another new commit (https://github.com/GarmanGroup/RIDL/commit/c858adc8bb85b15459db137a5f6222f204db0dca) to ensure that the input file only contains full absolute file paths. Apologies if this means your input file needs to be modified, however the relative paths for files were too ambiguous (are they relative to the input file, to the working directory or the runRIDL.py script). The program will now report an error message if the input file contains relative paths.
